// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ConsorcioContext))]
    [Migration("20260506134058_AgregadoTablaConsorcio")]
    partial class AgregadoTablaConsorcio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Consorcio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Altura")
                        .HasColumnType("int");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DiaVencimientoExpensas")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProvincia")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioCreador")
                        .HasColumnType("int");

                    b.Property<double?>("Latitud")
                        .HasColumnType("float");

                    b.Property<double?>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdProvincia");

                    b.HasIndex("IdUsuarioCreador");

                    b.ToTable("Consorcios");
                });

            modelBuilder.Entity("Model.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioExpensa")
                        .HasColumnType("int");

                    b.Property<string>("ArchivoComprobante")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGasto")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdConsorcio")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoGasto")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioCreador")
                        .HasColumnType("int");

                    b.Property<int>("MesExpensa")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdConsorcio");

                    b.HasIndex("IdTipoGasto");

                    b.HasIndex("IdUsuarioCreador");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("Model.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("Model.ReservaSum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EntregoCorrectamente")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSum")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("Turno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSum");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ReservaSum");
                });

            modelBuilder.Entity("Model.Sum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdConsorcio")
                        .HasColumnType("int");

                    b.Property<int?>("ReservaSumId")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdConsorcio");

                    b.HasIndex("ReservaSumId");

                    b.ToTable("Sum");
                });

            modelBuilder.Entity("Model.TipoGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TiposGasto");
                });

            modelBuilder.Entity("Model.Unidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoPropietario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmailPropietario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdConsorcio")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioCreador")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombrePropietario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Superficie")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdConsorcio");

                    b.HasIndex("IdUsuarioCreador");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaRegistracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Model.Consorcio", b =>
                {
                    b.HasOne("Model.Provincia", "Provincia")
                        .WithMany("Consorcios")
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Usuario", "UsuarioCreador")
                        .WithMany("Consorcios")
                        .HasForeignKey("IdUsuarioCreador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provincia");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("Model.Gasto", b =>
                {
                    b.HasOne("Model.Consorcio", "Consorcio")
                        .WithMany("Gastos")
                        .HasForeignKey("IdConsorcio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.TipoGasto", "TipoGasto")
                        .WithMany()
                        .HasForeignKey("IdTipoGasto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Usuario", "UsuarioCreador")
                        .WithMany("Gastos")
                        .HasForeignKey("IdUsuarioCreador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consorcio");

                    b.Navigation("TipoGasto");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("Model.ReservaSum", b =>
                {
                    b.HasOne("Model.Sum", "Sum")
                        .WithMany("Reservas")
                        .HasForeignKey("IdSum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Usuario", "UsuarioQueReserva")
                        .WithMany("Reservas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sum");

                    b.Navigation("UsuarioQueReserva");
                });

            modelBuilder.Entity("Model.Sum", b =>
                {
                    b.HasOne("Model.Consorcio", "Consorcio")
                        .WithMany("Sums")
                        .HasForeignKey("IdConsorcio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.ReservaSum", null)
                        .WithMany("Reservas")
                        .HasForeignKey("ReservaSumId");

                    b.Navigation("Consorcio");
                });

            modelBuilder.Entity("Model.Unidad", b =>
                {
                    b.HasOne("Model.Consorcio", "Consorcio")
                        .WithMany("Unidades")
                        .HasForeignKey("IdConsorcio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Usuario", "UsuarioCreador")
                        .WithMany("Unidades")
                        .HasForeignKey("IdUsuarioCreador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consorcio");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("Model.Consorcio", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("Sums");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("Model.Provincia", b =>
                {
                    b.Navigation("Consorcios");
                });

            modelBuilder.Entity("Model.ReservaSum", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Model.Sum", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Model.Usuario", b =>
                {
                    b.Navigation("Consorcios");

                    b.Navigation("Gastos");

                    b.Navigation("Reservas");

                    b.Navigation("Unidades");
                });
#pragma warning restore 612, 618
        }
    }
}
